logging:
  level:
    org:
      hibernate: INFO
      springframework:
        web: INFO
        security: DEBUG
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_employee-learning
    username: postgres
    password: 0000
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        id:
          uuid:
            generator: org.hibernate.id.UUIDGenerator
        jdbc:
          lob:
            non_contextual_creation: true
        jpa:
          show-sql: true
        connection:
          datasource:
            log-statement: true
